//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ladashopq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Application { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Tovars Tovars { get; set; }
        public virtual Users Users { get; set; }
    }
}
