//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ladashopq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public string Article { get; set; }
        public int CategoryID { get; set; }
        public int ModeID { get; set; }
        public int ProviderID { get; set; }
        public string Description { get; set; }
        public string ProductName { get; set; }
        public string Img { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Models Models { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
